[package]
name = "csvexample"
version = "0.1.0"
edition = "2021"

[dependencies]
dictionary_bitmap_trie = { path = "../../" }
csv = "1.3.0"
actix-web = "4"
actix-cors = "0.7.1"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.49.0"
serde_json = "1.0.149"